### ISSUE TITLE
Deprecated warning GuzzleHttp\Client  class is considered final

### ISSUE THREAD

**Issue by JLepeltier** [akamai-open/AkamaiOPEN-edgegrid-php#8]
Using php 8.1 we have the following deprecated warning : 

User Deprecated: The "GuzzleHttp\Client" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Akamai\Open\EdgeGrid\Client". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"GuzzleHttp\\Client\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Akamai\\Open\\EdgeGrid\\Client\". at /var/www/enrj-importer-php/vendor/symfony/error-handler/DebugClassLoader.php:333)"} []

**Comment by lkowalsk-akamai-com** [comment]
This should be resolved now.
