### ISSUE TITLE
Question: Release a version with PHP 7.4 support?

### ISSUE THREAD

**Issue by bmack** [akamai-open/AkamaiOPEN-edgegrid-php#9]
Hey maintainers,

I am currently struggling with updating 

* akamai-open/edgegrid-client
* akamai-open/edgegrid-auth

to v2, as it requires PHP 8.1, however, there is no PHP 7.4-compatible version with guzzle 7 in place, which I need as an intermediate step before our hosting provider is able to update to PHP 8.1.

As I noticed in the source code of this repo, it is possible to reduce the PHP version constraint in composer.json to use "^7.4 || ^8.1" without any further effort. This way, a new release is able for people to update their public packages with a better version constraint. After having a 7.4 compatible v2 release (2.0.1), we could then raise again to PHP 8.1+ again.

My question is this: Would you be willing for such a move, or should I create an official fork?

Another official alternative for me is to try to require Guzzle v7 in your akamai-open/edgegrid-* v1.x versions (in case this is still maintained).

Thanks for your feedback in advance!

**Comment by kaush-** [comment]
Hi @bmack,

Thank you for raising this issue with us. We will investigate internally and keep you posted if accepted.

Regards,
Piyush

**Comment by lkowalsk-akamai-com** [comment]
Hi @bmack,

We are not planning to support 7.x versions of PHP. Feel free to create fork on your own, but it will not be considered as official.
